### PR TITLE
js-polyfill: support Safari, which doesn't have instantiateStreaming

### LINKED ISSUE #134: Polyfill doesn't work on Safari 12.1
When I try to run a WebAssembly file in the polyfill at https://wasi.dev/polyfill/, I get

"Exception thrown, see JavaScript console" when I try to load the file.

In the console, I get:

"WebAssembly.instantiateStreaming is not a function. (In 'WebAssembly.instantiateStreaming(response, imports)', 'WebAssembly.instantiateStreaming' is undefined)"

I'm on macOS 10.14.4, Safari 12.1 (`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15`).

### PR DESCRIPTION
**Pull request by zhuowei**
This fixes #134.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Thanks!
